/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/app-passwords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/app-passwords`: list the calling user's app passwords. */
        get: operations["list_app_passwords"];
        put?: never;
        /** `POST /api/app-passwords`: create an app password for the calling user. */
        post: operations["create_app_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app-passwords/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * `DELETE /api/app-passwords/{key_id}`: revoke one of the calling
         *     user's app passwords.
         */
        delete: operations["delete_app_password"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/discovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /api/auth/discovery`: report which auth provider serves the given
         *     email. Defaults to Frontegg whenever Ory is not configured, the email is
         *     malformed, or the flag is off/unavailable — unless the stack sets
         *     `--ory-auth-default-enabled`, which flips the absent-flag fallback to
         *     Ory (personal stacks; a real LaunchDarkly flag always wins).
         */
        post: operations["discover_auth_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud-regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the available cloud regions for an organization */
        get: operations["get_cloud_regions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community-license-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issue_community_license_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/costs/breakdown/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the per-account, per-cluster cost breakdown bucketed by UTC day. */
        get: operations["get_cost_breakdown_daily"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/costs/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get daily costs for an organization */
        get: operations["get_current_organization_daily_costs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get credits for the current organization */
        get: operations["get_current_organization_credits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite a user to the calling admin's organization */
        post: operations["create_organization_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recent invoices from Orb for an organization
         *     This endpoint returns the 20 most recent invoices for the given user,
         *     including draft, paid, void, and issued invoices by default.
         */
        get: operations["get_invoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/license-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issue_license_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/license-key/revoked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_revoked_license_keys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the members of the calling user's organization */
        get: operations["list_organization_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{identity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from the calling admin's organization */
        delete: operations["remove_organization_member"];
        options?: never;
        head?: never;
        /** Change a member's role in the calling admin's organization */
        patch: operations["update_organization_member_role"];
        trace?: never;
    };
    "/api/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current organization */
        get: operations["get_current_organization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organization/intercom/jwt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a JWT for Intercom authentication */
        post: operations["issue_intercom_jwt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organization/onboarded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboard_current_organization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organization/payment-methods/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["make_payment_method_default"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organization/payment-methods/detach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["detach_payment_method"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organization/payment-methods/setup-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_setup_intent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/self-managed-subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_self_managed_subscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Costs for all tracked resources. */
        AllCosts: {
            /** @description Compute resource costs. */
            compute: components["schemas"]["Cost_ComputePrice"];
            /** @description Storage resource costs. */
            storage: components["schemas"]["Cost_StoragePrice"];
        };
        AuthDiscoveryRequest: {
            /** @description The email the user is trying to log in or sign up with. */
            email: string;
        };
        AuthDiscoveryResponse: {
            /** @description The auth provider the caller should use. */
            provider: components["schemas"]["AuthProviderKind"];
        };
        /** @enum {string} */
        AuthProviderKind: "frontegg" | "ory";
        Card: {
            /** @description The last 4 digits of the card number. */
            last4: string;
            /**
             * Format: int64
             * @description The expiration month of the card.
             */
            expMonth: number;
            /**
             * Format: int64
             * @description The expiration year of the card.
             */
            expYear: number;
        };
        /** @description The price for a specific class of compute resource. */
        ComputePrice: {
            /** @description The ID of the region in which the compute resource was used (e.g., `aws/us-east-1`). */
            regionId: string;
            /** @description The size of the compute resource replica (e.g., `xsmall`) */
            replicaSize: string;
            /** @description The rate per unit of usage. */
            unitAmount: string;
            /** @description The total cost for the resource type in the region, excluding any minimums and discounts. */
            subtotal: string;
        };
        /** @description Cost breakdown for one Orb account (parent or child) within a billing period. */
        CostBreakdownAccount: {
            external_customer_id: string;
            clusters: components["schemas"]["CostBreakdownCluster"][];
        };
        /** @description Per-cluster cost breakdown for a single Orb account within a billing period. */
        CostBreakdownCluster: {
            /** @description The environment that owns this cluster (event property `environment_id`). */
            environment_id: string;
            /**
             * @description Human-readable cluster key in `cluster_name.replica_name` form
             *     (event property `cluster_grouping_key`). Empty for storage/egress rows
             *     that have no per-cluster breakdown.
             */
            cluster_grouping_key: string;
            /**
             * @description Resource category for rows that aren't a compute cluster — "Storage" or
             *     "Egress", derived from the Orb price's item name — so storage and egress
             *     (which share an empty `cluster_grouping_key`) render as separate rows.
             *     Empty for compute rows, which are identified by `cluster_grouping_key`.
             */
            category: string;
            /**
             * @description Cloud region in `provider/region` form, e.g. "aws/us-east-1" (event
             *     property `region`). Lets the frontend qualify each row ("aws/us-east-1 /
             *     Storage"), matching the daily "Spend between …" table.
             */
            region: string;
            /** @description Map from price_id to the computed dollar amount (e.g. "1.23"). */
            amounts: {
                [key: string]: string;
            };
        };
        /** @description Per-account cost breakdown for a single calendar day. */
        CostBreakdownDay: {
            /**
             * Format: date-time
             * @description Start of the day (inclusive).
             */
            startDate: string;
            /**
             * Format: date-time
             * @description End of the day (exclusive).
             */
            endDate: string;
            accounts: components["schemas"]["CostBreakdownAccount"][];
        };
        /** @description The daily costs for a given customer. */
        CostBucket: {
            /** @description All resource costs */
            costs: components["schemas"]["AllCosts"];
            /** @description The total cost for the timeframe, excluding any minimums and discounts. */
            subtotal: string;
            /** @description The total cost for the timeframe, including any minimums and discounts. */
            total: string;
            /**
             * Format: date-time
             * @description The date on which the bucket timeframe starts.
             */
            startDate: string;
            /**
             * Format: date-time
             * @description The date on which the bucket timeframe ends.
             */
            endDate: string;
        };
        Cost_ComputePrice: {
            /**
             * @description The resource-specific pricing breakdown. Either `ComputePrice`,
             *     `NetworkPrice`, or `StoragePrice`.
             */
            prices: {
                /** @description The ID of the region in which the compute resource was used (e.g., `aws/us-east-1`). */
                regionId: string;
                /** @description The size of the compute resource replica (e.g., `xsmall`) */
                replicaSize: string;
                /** @description The rate per unit of usage. */
                unitAmount: string;
                /** @description The total cost for the resource type in the region, excluding any minimums and discounts. */
                subtotal: string;
            }[];
            /**
             * @description The total cost for the resource in the timeframe, excluding any
             *     minimums and discounts.
             */
            subtotal: string;
            /**
             * @description The total cost for the resource in the timeframe, including any
             *     minimums and discounts.
             */
            total: string;
        };
        Cost_NetworkPrice: {
            /**
             * @description The resource-specific pricing breakdown. Either `ComputePrice`,
             *     `NetworkPrice`, or `StoragePrice`.
             */
            prices: {
                /** @description The ID of the region in which the network resource was used (e.g., `aws/us-east-1`). */
                regionId: string;
                /** @description The rate per unit of usage. */
                unitAmount: string;
                /** @description The total cost for the resource type in the region, excluding any minimums and discounts. */
                subtotal: string;
            }[];
            /**
             * @description The total cost for the resource in the timeframe, excluding any
             *     minimums and discounts.
             */
            subtotal: string;
            /**
             * @description The total cost for the resource in the timeframe, including any
             *     minimums and discounts.
             */
            total: string;
        };
        Cost_StoragePrice: {
            /**
             * @description The resource-specific pricing breakdown. Either `ComputePrice`,
             *     `NetworkPrice`, or `StoragePrice`.
             */
            prices: {
                /** @description The ID of the region in which the storage resource was used (e.g., `aws/us-east-1`). */
                regionId: string;
                /** @description The rate per unit of usage. */
                unitAmount: string;
                /** @description The total cost for the resource type in the region, excluding any minimums and discounts. */
                subtotal: string;
            }[];
            /**
             * @description The total cost for the resource in the timeframe, excluding any
             *     minimums and discounts.
             */
            subtotal: string;
            /**
             * @description The total cost for the resource in the timeframe, including any
             *     minimums and discounts.
             */
            total: string;
        };
        CreateAppPasswordRequest: {
            /** @description Human-readable name for the app password. */
            name: string;
        };
        CreateAppPasswordResponse: components["schemas"]["IssuedApiKey"] & {
            /** @description The app password secret. Only returned once, at creation. */
            secret: string;
        };
        CreateCommunityLicenseKeyRequest: {
            email: string;
            environmentId?: string | null;
            licenseKey?: string | null;
        };
        CreateInviteRequest: {
            /** @description Email address of the user to invite. */
            email: string;
            /** @description The role the invitee will hold. */
            role: components["schemas"]["OrgRole"];
        };
        CreateInviteResponse: {
            /**
             * @description The raw invite token. Returned exactly once; the server stores only
             *     its hash.
             */
            inviteToken: string;
            /**
             * Format: date-time
             * @description When the invitation expires.
             */
            expiresAt: string;
        };
        CreateLicenseKeyRequest: {
            /** Format: uuid */
            environmentId?: string | null;
        };
        CreateLicenseKeyResponse: {
            licenseKey: string;
        };
        /** @description A block of credit held by a customer. */
        CreditBlock: {
            /**
             * Format: double
             * @description The available value in this block of credits.
             */
            balance: number;
            /** @description The amount paid per credit. */
            perUnitCostBasis?: string | null;
        };
        /**
         * @description Response for `GET /api/costs/breakdown/daily` — the per-account,
         *     per-cluster breakdown bucketed by UTC day. Dense: one entry per UTC day in
         *     the requested window, with empty `accounts` for days that had no usage.
         */
        DailyCostBreakdownResponse: {
            days: components["schemas"]["CostBreakdownDay"][];
        };
        /** @description The daily costs for a given customer. */
        DailyCostResponse: {
            /** @description The available value in this block of credits, excluding any minimums and discounts. */
            subtotal: string;
            /** @description The available value in this block of credits, including any minimums and discounts. */
            total: string;
            /** @description The amount paid per credit. */
            daily: components["schemas"]["CostBucket"][];
        };
        DetachPaymentMethodRequest: {
            paymentMethodId: string;
        };
        GetSelfManagedSubscriptionResponse: {
            /** Format: date-time */
            endDate: string;
        };
        /** @description Response containing a JWT token for Intercom authentication */
        IntercomJwtResponse: {
            /** @description The JWT token for Intercom authentication */
            jwt: string;
        };
        Invoice: {
            /**
             * Format: date-time
             * @description The issue date of the invoice.
             */
            issueDate: string;
            /**
             * @description The URL at which a PDF representation of the invoice can be retrieved.
             *
             *     Typically `None` for `draft` invoices, in which case `html_url` should
             *     be `Some`, though this is not guaranteed by the Orb API documentation.
             */
            pdfUrl?: string | null;
            /** @description An ISO 4217 currency string, or "credits" */
            currency: string;
            /** @description The total after any minimums, discounts, and taxes have been applied. */
            total: string;
            /** @description The amount the customer will be charged due to this invoice */
            amountDue: string;
            /**
             * Format: date-time
             * @description The time at which the invoice was created.
             */
            createdAt: string;
            /**
             * @description The URL at which a web-page representation of the invoice can be retrieved.
             *
             *     May be `None`, typically after the invoice is well past its issue date, in which
             *     case `pdf_url` should be `Some`, although this is not guaranteed by the Orb
             *     API documentation.
             */
            webUrl?: string | null;
            /** @description The status (see [`orb_billing::InvoiceStatusFilter`] for details). */
            status: string;
            /** @description An automatically generated number to help track and reconcile invoices. */
            invoiceNumber: string;
        };
        IpAddress: {
            ip: string;
        };
        /**
         * @description An issued API key, as returned by Talos. The key's secret is only
         *     present in the issue response and is never returned by list/get.
         */
        IssuedApiKey: {
            key_id: string;
            actor_id: string;
            name?: string | null;
            status?: string | null;
            create_time?: string | null;
            expire_time?: string | null;
            last_used_time?: string | null;
        };
        ListRevokedLicenseKeysResponse: {
            jtis: string[];
        };
        MakePaymentMethodDefaultRequest: {
            paymentMethodId: string;
        };
        /**
         * @description The marketplace through which an organization is billed.
         * @enum {string}
         */
        Marketplace: "aws" | "direct";
        /** @description The price for a specific class of network resource. */
        NetworkPrice: {
            /** @description The ID of the region in which the network resource was used (e.g., `aws/us-east-1`). */
            regionId: string;
            /** @description The rate per unit of usage. */
            unitAmount: string;
            /** @description The total cost for the resource type in the region, excluding any minimums and discounts. */
            subtotal: string;
        };
        /**
         * @description Role of an organization member. `Admin` corresponds to the
         *     `MaterializePlatformAdmin` role the token hook stamps into tokens; the
         *     membership row is the source the token hook derives `metadata_admin`
         *     from (see `crate::ory::roles`), with identity metadata as fallback.
         * @enum {string}
         */
        OrgRole: "admin" | "member";
        /** @description A member of the calling user's organization. */
        OrganizationMember: {
            /**
             * Format: uuid
             * @description The member's identity id.
             */
            id: string;
            /** @description The member's email address. */
            email: string;
            /** @description The member's role in the organization. */
            role: components["schemas"]["OrgRole"];
            /**
             * Format: date-time
             * @description When the member joined the organization.
             */
            joinedAt: string;
        };
        OrganizationResponse: {
            /**
             * Format: uuid
             * @description The Organization ID (aka Frontegg ID).
             */
            id: string;
            /** @description The name of the organization. */
            name: string;
            /** @description Whether or not the organization is permitted to provision new Materialize environments. */
            blocked: boolean;
            /** @description Whether or not the organization has been flagged as having completed onboarding. */
            onboarded: boolean;
            subscription?: null | components["schemas"]["Subscription"];
            /**
             * Format: date-time
             * @description The date the organization's trial ends.
             */
            trialExpiresAt?: string | null;
            /** @description PaymentMethods */
            paymentMethods?: components["schemas"]["PaymentMethod"][] | null;
            /** @description The ID of the default payment method for the organization. */
            defaultPaymentMethodId?: string | null;
        };
        /** @description All API responses that return a list use this standard pagination envelope */
        Paginated_CreditBlock: {
            /** @description The data in this page. */
            data: {
                /**
                 * Format: double
                 * @description The available value in this block of credits.
                 */
                balance: number;
                /** @description The amount paid per credit. */
                perUnitCostBasis?: string | null;
            }[];
            /**
             * @description The cursor to provide to the next API call to retrieve the next
             *     page of results.
             *
             *     Set to `None` if there are no further pages.
             */
            nextCursor?: string | null;
        };
        /** @description All API responses that return a list use this standard pagination envelope */
        Paginated_Invoice: {
            /** @description The data in this page. */
            data: {
                /**
                 * Format: date-time
                 * @description The issue date of the invoice.
                 */
                issueDate: string;
                /**
                 * @description The URL at which a PDF representation of the invoice can be retrieved.
                 *
                 *     Typically `None` for `draft` invoices, in which case `html_url` should
                 *     be `Some`, though this is not guaranteed by the Orb API documentation.
                 */
                pdfUrl?: string | null;
                /** @description An ISO 4217 currency string, or "credits" */
                currency: string;
                /** @description The total after any minimums, discounts, and taxes have been applied. */
                total: string;
                /** @description The amount the customer will be charged due to this invoice */
                amountDue: string;
                /**
                 * Format: date-time
                 * @description The time at which the invoice was created.
                 */
                createdAt: string;
                /**
                 * @description The URL at which a web-page representation of the invoice can be retrieved.
                 *
                 *     May be `None`, typically after the invoice is well past its issue date, in which
                 *     case `pdf_url` should be `Some`, although this is not guaranteed by the Orb
                 *     API documentation.
                 */
                webUrl?: string | null;
                /** @description The status (see [`orb_billing::InvoiceStatusFilter`] for details). */
                status: string;
                /** @description An automatically generated number to help track and reconcile invoices. */
                invoiceNumber: string;
            }[];
            /**
             * @description The cursor to provide to the next API call to retrieve the next
             *     page of results.
             *
             *     Set to `None` if there are no further pages.
             */
            nextCursor?: string | null;
        };
        /** @description All API responses that return a list use this standard pagination envelope */
        Paginated_Region: {
            /** @description The data in this page. */
            data: {
                /** @description A unique identifier for the region, e.g. `aws/us-east-1` */
                id: string;
                /** @description The (provider-specific) region string -- e.g. `us-east-1` */
                name: string;
                /** @description The cloud provider hosting the region. Currently this can only be "aws" */
                cloudProvider: string;
                /** @description The URL at which the Region API can be reached */
                url: string;
            }[];
            /**
             * @description The cursor to provide to the next API call to retrieve the next
             *     page of results.
             *
             *     Set to `None` if there are no further pages.
             */
            nextCursor?: string | null;
        };
        PaymentMethod: {
            /** @description The type of payment method (e.g. "card"). */
            type: string;
            card?: null | components["schemas"]["Card"];
            /** @description The ID of the payment method. */
            id: string;
            /**
             * Format: int64
             * @description The UNIX timestamp of when the payment method was created.
             */
            created: number;
            /** @description Whether this is the default payment method for the organization. */
            defaultPaymentMethod: boolean;
        };
        /**
         * @description Possible plans that customers may be subscribed to.
         * @enum {string}
         */
        PlanType: "capacity" | "evaluation" | "internal" | "on-demand" | "partner" | "uncategorized";
        /** @description Describe a cloud region in which Materialize is available -- for example, AWS's `us-east-1` */
        Region: {
            /** @description A unique identifier for the region, e.g. `aws/us-east-1` */
            id: string;
            /** @description The (provider-specific) region string -- e.g. `us-east-1` */
            name: string;
            /** @description The cloud provider hosting the region. Currently this can only be "aws" */
            cloudProvider: string;
            /** @description The URL at which the Region API can be reached */
            url: string;
        };
        SetupIntent: {
            /** @description The ID of the SetupIntent. */
            id: string;
            /** @description The client secret of the SetupIntent, used to complete setup from your frontend. */
            clientSecret: string;
            /** @description The status of the SetupIntent. */
            status: string;
        };
        /** @description The price for a specific class of storage resource. */
        StoragePrice: {
            /** @description The ID of the region in which the storage resource was used (e.g., `aws/us-east-1`). */
            regionId: string;
            /** @description The rate per unit of usage. */
            unitAmount: string;
            /** @description The total cost for the resource type in the region, excluding any minimums and discounts. */
            subtotal: string;
        };
        Subscription: {
            /** @description Possible plans that customers may be subscribed to. */
            type: components["schemas"]["PlanType"];
            /** @description The marketplace the organization is billed through. */
            marketplace: components["schemas"]["Marketplace"];
        };
        UpdateMemberRoleRequest: {
            /** @description The member's new role. */
            role: components["schemas"]["OrgRole"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_app_passwords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The calling user's app passwords */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedApiKey"][];
                };
            };
            /** @description App passwords for this organization are managed by Frontegg */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description App-password management is not available on this stack */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_app_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAppPasswordRequest"];
            };
        };
        responses: {
            /** @description The created app password; the secret is only returned once */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAppPasswordResponse"];
                };
            };
            /** @description App passwords for this organization are managed by Frontegg */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description App-password management is not available on this stack */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_app_password: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The app password's key ID */
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The app password was revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such app password owned by the calling user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    discover_auth_provider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthDiscoveryRequest"];
            };
        };
        responses: {
            /** @description The auth provider serving this email */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthDiscoveryResponse"];
                };
            };
            /** @description Invalid email */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_cloud_regions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cloud Regions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paginated_Region"];
                };
            };
        };
    };
    issue_community_license_key: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommunityLicenseKeyRequest"];
            };
        };
        responses: {
            /** @description License key signed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateLicenseKeyResponse"];
                };
            };
            /** @description Invalid environment id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to issue license key */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_cost_breakdown_daily: {
        parameters: {
            query: {
                /** @example 2026-06-17 */
                startDate: string;
                /** @example 2026-06-17 */
                endDate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization Daily Cost Breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyCostBreakdownResponse"];
                };
            };
            /** @description Missing or invalid startDate/endDate query params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_current_organization_daily_costs: {
        parameters: {
            query: {
                startDate: string;
                endDate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization Daily Costs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyCostResponse"];
                };
            };
        };
    };
    get_current_organization_credits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization Credits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paginated_CreditBlock"];
                };
            };
        };
    };
    create_organization_invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteRequest"];
            };
        };
        responses: {
            /** @description The created invitation; the token is only returned once */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInviteResponse"];
                };
            };
            /** @description Invalid email address */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The invitee is already a member, or members for this organization are managed by Frontegg */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_invoices: {
        parameters: {
            query?: {
                /** @description Include draft invoices. */
                draft?: boolean;
                /** @description Include issued invoices. */
                issued?: boolean;
                /** @description Include paid invoices. */
                paid?: boolean;
                /** @description Include voided invoices. */
                void?: boolean;
                /** @description Include synced invoices. */
                synced?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paginated_Invoice"];
                };
            };
            /** @description No permissions to get invoices */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issue_license_key: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLicenseKeyRequest"];
            };
        };
        responses: {
            /** @description License key signed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateLicenseKeyResponse"];
                };
            };
            /** @description Cannot specify an environment id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subscription has expired */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to issue license key */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_revoked_license_keys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked license key JTIs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRevokedLicenseKeysResponse"];
                };
            };
            /** @description Failed to list revoked license keys */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_organization_members: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The organization's members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMember"][];
                };
            };
            /** @description Members for this organization are managed by Frontegg */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_organization_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The member's identity id */
                identity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member was removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admins cannot remove themselves */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such member */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Members for this organization are managed by Frontegg */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_organization_member_role: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The member's identity id */
                identity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRoleRequest"];
            };
        };
        responses: {
            /** @description The member's role was updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such member */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Members for this organization are managed by Frontegg */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_current_organization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
        };
    };
    issue_intercom_jwt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intercom JWT */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntercomJwtResponse"];
                };
            };
            /** @description No permissions to issue Intercom JWT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to issue JWT */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    onboard_current_organization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Onboarding state successfully set */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    make_payment_method_default: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MakePaymentMethodDefaultRequest"];
            };
        };
        responses: {
            /** @description Payment method set as default */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detach_payment_method: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetachPaymentMethodRequest"];
            };
        };
        responses: {
            /** @description Payment method detached */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_setup_intent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Create SetupIntent for new Stripe Payment Method */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupIntent"];
                };
            };
        };
    };
    get_self_managed_subscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSelfManagedSubscriptionResponse"];
                };
            };
            /** @description Cannot specify an environment id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subscription has expired */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to get customer subscription from orb */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
